version: '3.7'
services:
  flask:
    build: .
    container_name: Fibonachi
    ports:
      - "8081:8081"
    depends_on:
      - cache
  cache:
   image: memcached
   ports:
     - "11211:11211"
   entrypoint:
    - memcached
    - -m 64
